# Generated by Django 2.1.5 on 2019-03-04 10:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('assembly', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('srname', models.CharField(max_length=30)),
                ('r_name', models.CharField(max_length=30)),
                ('r_srname', models.CharField(max_length=30)),
                ('relation', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('houseno', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('town', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=30)),
                ('email_id', models.CharField(max_length=30)),
                ('mo_number', models.CharField(max_length=30)),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='photos/'), upload_to='')),
                ('age_p', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='photos/'), upload_to='')),
                ('typeageproof', models.CharField(max_length=30)),
                ('add_p', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='photos/'), upload_to='')),
                ('typeaddproof', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
            ],
        ),
    ]
