# Generated by Django 2.1.5 on 2019-03-10 14:14

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterid', '0003_auto_20190310_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='photos/'), upload_to=''),
        ),
    ]
