# Generated by Django 2.1.5 on 2019-03-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterid', '0005_auto_20190310_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('suggestion', models.CharField(max_length=500)),
            ],
        ),
    ]
