# Generated by Django 2.1.5 on 2019-03-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterid', '0006_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Nope', max_length=30),
        ),
    ]
