# Generated by Django 2.1.5 on 2019-03-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterid', '0007_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
