# Generated by Django 2.1.5 on 2019-03-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterid', '0008_auto_20190316_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='delete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('assembly', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=30)),
                ('voterid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('srname', models.CharField(max_length=30)),
                ('delete', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=30)),
                ('email_id', models.CharField(max_length=30)),
                ('houseno', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('town', models.CharField(max_length=30)),
                ('mo_number', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
            ],
        ),
    ]
