# Generated by Django 2.1.5 on 2019-03-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterid', '0009_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='add_p',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='modification',
            name='age_p',
            field=models.FileField(upload_to=''),
        ),
    ]
