# Generated by Django 2.1.5 on 2019-03-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evoterid', '0010_auto_20190320_2206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='delete',
            new_name='deletetable',
        ),
    ]
