# Generated by Django 2.1.5 on 2019-04-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterid', '0011_auto_20190323_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='Nope', max_length=30),
        ),
    ]
