# Generated by Django 2.1.5 on 2019-04-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterid', '0012_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='Not verified', max_length=30),
        ),
    ]
