# Generated by Django 2.1.5 on 2019-04-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterid', '0013_auto_20190405_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='add_p',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='age_p',
            field=models.FileField(upload_to=''),
        ),
    ]
