# Generated by Django 2.1.5 on 2019-04-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterid', '0014_auto_20190405_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='target',
            field=models.CharField(default='Nope', max_length=30),
        ),
    ]
