# Generated by Django 2.1.5 on 2019-04-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterid', '0015_suggestion_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletetable',
            name='photo',
            field=models.FileField(default='Nope', upload_to=''),
        ),
    ]
