# Generated by Django 2.1.5 on 2019-04-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterid', '0016_deletetable_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletetable',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
